variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: "tcp://docker:2375"
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public

stages:
    - Static analyzes
    - Testing

default:
    image: shopware/development:latest
    before_script:
        - zip -rq plugin.zip .
        - git clone --branch 6.0+ea http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform
        - unzip -q plugin.zip -d development/custom/plugins/SwagPayPal
        - cd development
        - cd platform && git checkout 6.0+ea && cd ..
        - composer require shopware/platform dev-master --no-update --no-suggest --no-scripts
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

# Stage: static

PHP analyze:
    stage: Static analyzes
    script:
        - composer install --no-interaction --optimize-autoloader --no-suggest --no-scripts
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagPayPal
        - bin/phpstan.sh
        - cd $CI_PROJECT_DIR/development
        - php vendor/shopware/platform/bin/php-cs-fixer.phar fix --config=vendor/shopware/platform/.php_cs.dist --dry-run -vvv --allow-risky=yes --format=junit custom/plugins/SwagPayPal | tee php-cs-fixer.xml
    artifacts:
        reports:
            junit: development/php-cs-fixer.xml

PHPUnit (MariaDB):
    stage: Testing
    services:
        -   name: mariadb:10.3
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagPayPal
        - composer dump-autoload -d custom/plugins/SwagPayPal
        - ./psh.phar init-test-databases
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SwagPayPal/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text

    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml
