variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: 'tcp://docker:2375'
    MYSQL_ROOT_PASSWORD: app
    WEB_DOCUMENT_ROOT: $CI_PROJECT_DIR/development/public
    DEV_IMAGE: shopware/development:7.4-composer-2
    CORE_BRANCH: "trunk"
    CMS_EXTENSION_BRANCH: "master"
    RUN_IN_MR: "true"
    MYSQL_IMAGE: mysql:5.7
    MYSQL_CMD: mysqld

stages:
    - Static analysis
    - Testing

default:
    image: $DEV_IMAGE
    before_script:
        - zip -rq plugin.zip .
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/development.git --branch $CORE_BRANCH
        - rm -rf development/platform
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/product/platform.git development/platform --branch $CORE_BRANCH
        - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.shopware.com/shopware/6/services/cms-extensions.git development/custom/plugins/SwagCmsExtensions --branch $CMS_EXTENSION_BRANCH
        - unzip -q plugin.zip -d development/custom/plugins/SwagPayPal
        - cd development
        - composer dump-autoload -d custom/plugins/SwagCmsExtensions
        - cp -v dev-ops/gitlab/.psh.yaml.override .
        - /entrypoint supervisord > /dev/null 2>&1 &

Check built JS files:
    only:
        refs:
            - merge_requests
            - master
            - schedules
            - pipelines
    stage: Static analysis
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagPayPal
        - ./psh.phar storefront:install-dependencies
        - ./psh.phar administration:build
        - ./psh.phar storefront:build
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagPayPal
        - >
            if ! git diff --quiet --ignore-submodules HEAD --; then
                echo "Built Javascript files differ. Update the dependencies and execute 'administration:build' and 'storefront:build' again";
                git status;
                exit 1;
            else
                echo "Everything ok"
                exit 0;
            fi
    allow_failure: true

Static analyze:
    stage: Static analysis
    only:
        refs:
            - merge_requests
            - master
            - schedules
            - pipelines
    services:
        -   name: mysql:5.7
            alias: mysql
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagPayPal
        - cd $CI_PROJECT_DIR/development/custom/plugins/SwagPayPal
        - if [[ -n $CI_COMMIT_BRANCH ]]; then bin/check-todos.sh $CI_COMMIT_BRANCH; else bin/check-todos.sh $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME; fi
        - >
            if [[ $CORE_BRANCH = "trunk" ]]; then
                php ../../../dev-ops/analyze/vendor/bin/ecs check --config=../../../vendor/shopware/platform/easy-coding-standard.php src tests
                php ../../../dev-ops/analyze/vendor/bin/ecs check --config=easy-coding-standard.php
            fi
        - composer dump-autoload
        - php bin/phpstan-config-generator.php
        - php ../../../dev-ops/analyze/vendor/bin/phpstan analyze --configuration phpstan.neon src tests
        - php ../../../dev-ops/analyze/vendor/bin/psalm --config=psalm.xml --threads=$(nproc) --diff --show-info=false
        - >
            if [[ $CORE_BRANCH = "trunk" ]]; then
                cd $CI_PROJECT_DIR/development
                ./psh.phar administration:init --APP_ENV="dev"
                cd $CI_PROJECT_DIR/development/custom/plugins/SwagPayPal
                make administration-lint
                make storefront-lint
            fi
        # ToDo tag:v4.0.0 - use again
        # - cd $CI_PROJECT_DIR/development
        # - php bin/console dal:validate
    parallel:
        matrix:
            -   DEV_IMAGE:
                - shopware/development:7.4-composer-2
                - shopware/development:8.0-composer-2
            -   CORE_BRANCH:
                - 6.4.0.0
                - 6.4.1.0
                - trunk

PHPUnit:
    stage: Testing
    services:
          -   name: $MYSQL_IMAGE
              alias: mysql
              entrypoint: [ "sh", "-c", "docker-entrypoint.sh $MYSQL_CMD" ]
    coverage: '/^\s*Lines:\s*(\d+(?:\.\d+)?%)/'
    artifacts:
        paths:
            - development/build/artifacts/phpunit.clover.xml
        reports:
            junit: development/build/artifacts/phpunit.junit.xml
    script:
        - ./psh.phar init
        - php bin/console plugin:install --activate SwagPayPal
        - php bin/console plugin:install --activate SwagCmsExtensions
        - ./psh.phar init-test-databases
        - composer dump-autoload -d custom/plugins/SwagPayPal
        - touch custom/plugins/SwagPayPal/vendor/composer/InstalledVersions.php
        - php -d pcov.enabled=1 -d pcov.directory=$CI_PROJECT_DIR
            vendor/bin/phpunit
            --configuration custom/plugins/SwagPayPal/phpunit.xml.dist
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never
            --coverage-clover build/artifacts/phpunit.clover.xml
            --coverage-html build/artifacts/phpunit-coverage-html
            --coverage-text
        - php bin/console plugin:uninstall SwagPayPal
    rules:
        -   if: '$CI_MERGE_REQUEST_LABELS =~ /.*unit::all.*/'
        -   if: '$CI_MERGE_REQUEST_LABELS =~ /.*unit::skip.*/'
            when: never
        -   if: '$CI_COMMIT_BRANCH == "master"'
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
            changes:
                - "Migration*.php"
                - "**/Migration*.php"
        -   if: '$RUN_IN_MR == "true" && $CI_PIPELINE_SOURCE == "merge_request_event"'
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
            when: manual
            allow_failure: true
    parallel:
        matrix:
            # ToDo: Use working MariaDB version with https://jira.mariadb.org/browse/MDEV-25672 fixed
            -   MYSQL_IMAGE: mariadb:10.4.18
                DEV_IMAGE: shopware/development:8.0-composer-2
                CORE_BRANCH: [ "6.4.0.0", "6.4.1.0", "trunk" ]
            -   MYSQL_IMAGE:
                    - mysql:5.7
                    # ToDo: Use working MariaDB version with https://jira.mariadb.org/browse/MDEV-25672 fixed
                    - mariadb:10.3.28
                DEV_IMAGE: [ "shopware/development:7.4-composer-2", "shopware/development:8.0-composer-2" ]
                CORE_BRANCH: [ "6.4.0.0", "6.4.1.0", "trunk" ]
                RUN_IN_MR: "false"
            -   MYSQL_IMAGE:
                    - mysql:8.0.19
                DEV_IMAGE: [ "shopware/development:7.4-composer-2", "shopware/development:8.0-composer-2" ]
                CORE_BRANCH: [ "6.4.0.0", "6.4.1.0", "trunk" ]
                MYSQL_CMD: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql-require-primary-key=ON'
                RUN_IN_MR: "false"
